### ISSUE TITLE
Can you help me with this error

### ISSUE THREAD

**Issue by NagaRavi259** [Jijinr/Frwdit-V2#2]
It works fine for first channel after the first channel ID completed when im try to set for second channel it showing error
`Error: Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")`
Log 
`[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMessage")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
Unclosed tags: <code> (x1)
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
Unclosed tags: <code> (x1)
Unclosed tags: <code> (x1)
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMessage")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMessage")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMessage")
[bot] Sleeping for 3s (required by "messages.SendMedia")
[bot] Sleeping for 3s (required by "messages.SendMessage")
Service messages cannot be copied. chat_id: -1001393256003, message_id: 1
Agent47 with for Pyrogram v1.3.6 (Layer 136) started on @Agent247_bot.
Userbot Account micro started
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMessage")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")
Telegram says: [403 CHAT_WRITE_FORBIDDEN] - You don't have rights to send messages in this chat (caused by "messages.SendMedia")`

**Comment by Jijinr** [comment]
😑
